### ISSUE TITLE
Running telegraf and telegraf_datagen into containers

### ISSUE THREAD

**Issue by vinodborole** [sledigabel/telegraf_datagen#1]
While i am running telegraf and telegraf_datagen into containers i don't see the data getting exchanged, can you tell me what configurations should i change in telegraf.conf and in telegraf_datagen.conf to make this work?

**Comment by sledigabel** [comment]
did you fix this problem @vinodborole ?
The configuration in telegraf_datagen.conf should be tweakable.
I have not touched this project in years but don't see a reason why this should work any more.
